### ISSUE TITLE
How to get selected time.

### ISSUE THREAD

**Issue by nomimalik1769** [Endore8/TimePicker#2]
I am using this library and I am unable to figure out. how to get selected time from the view.

**Comment by endore8** [comment]
There is a public property `time: TimeInterval`. Does it help?

**Comment by nomimalik1769** [comment]
It's returning only time interval which is in this format like 45376.5. but what I want is like this 08:00 AM

**Comment by endore8** [comment]
Formatting you have to do yourself, e.g.:
```
let hour   = time - time.truncatingRemainder(dividingBy: 60 * 60)
let minute = time - hour
```
